name: Firebase Deploy Prod

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo npm ci
          sudo npm install -g firebase-tools
          sudo npm install -g @angular/cli
      - name: Build Prod App
        run: |
          ng build --prod
      - name: Firebase Deploy Prod
        run: |
          firebase use sbd-main-blog --token ${{ secrets.FIREBASE_CI_TOKEN }}
          firebase deploy --token ${{ secrets.FIREBASE_CI_TOKEN }} --non-interactive
